### ISSUE TITLE
'controller/input.cpp' BUILD ERROR

### ISSUE THREAD

**Issue by human2154** [medusalix/xow#178]
Hello. I'd like to use Xbox Series X controller with a wireless Dongle at Ubuntu 16.04.
I can read controller's data with 'xpad' when wired.

But when I try to use 'xow' there's some build error.
My errors are same as below.

/////////////////////////////////////////////////////////////////////////
im@xeno-pc2:~/xow$ make BUILD=RELEASE
g++  -Wall -Wpedantic -std=c++11 -MMD -MP -O3 -DVERSION=\"v0.5-27-g700529b\" -c -o xow.o xow.cpp
g++  -Wall -Wpedantic -std=c++11 -MMD -MP -O3 -DVERSION=\"v0.5-27-g700529b\" -c -o dongle/mt76.o dongle/mt76.cpp
g++  -Wall -Wpedantic -std=c++11 -MMD -MP -O3 -DVERSION=\"v0.5-27-g700529b\" -c -o dongle/dongle.o dongle/dongle.cpp
g++  -Wall -Wpedantic -std=c++11 -MMD -MP -O3 -DVERSION=\"v0.5-27-g700529b\" -c -o dongle/usb.o dongle/usb.cpp
g++  -Wall -Wpedantic -std=c++11 -MMD -MP -O3 -DVERSION=\"v0.5-27-g700529b\" -c -o controller/controller.o controller/controller.cpp
g++  -Wall -Wpedantic -std=c++11 -MMD -MP -O3 -DVERSION=\"v0.5-27-g700529b\" -c -o controller/input.o controller/input.cpp
controller/input.cpp: In member function ‘void InputDevice::addAxis(uint16_t, InputDevice::AxisConfig)’:
controller/input.cpp:76:5: error: ‘uinput_abs_setup’ was not declared in this scope
     uinput_abs_setup setup = {};
     ^
controller/input.cpp:78:5: error: ‘setup’ was not declared in this scope
     setup.code = code;
     ^
controller/input.cpp:84:21: error: ‘UI_ABS_SETUP’ was not declared in this scope
     if (ioctl(file, UI_ABS_SETUP, &setup) < 0)
                     ^
controller/input.cpp: In member function ‘void InputDevice::create(std::__cxx11::string, InputDevice::DeviceConfig)’:
controller/input.cpp:102:5: error: ‘uinput_setup’ was not declared in this scope
     uinput_setup setup = {};
     ^
controller/input.cpp:104:5: error: ‘setup’ was not declared in this scope
     setup.id.bustype = BUS_USB;
     ^
controller/input.cpp:113:21: error: ‘UI_DEV_SETUP’ was not declared in this scope
         ioctl(file, UI_DEV_SETUP, &setup) < 0 ||
                     ^
Makefile:32: recipe for target 'controller/input.o' failed
make: *** [controller/input.o] Error 1

**Comment by mjbogusz** [comment]
The missing `uinput_abs_setup` struct comes from the Linux's `uinput.h` header, it was added in December 2015 (https://github.com/torvalds/linux/commit/052876f8e5aec887d22c4d06e54aa5531ffcec75) and it made it into the 4.5 release.

Considering that Ubuntu 16.04 by default uses the 4.4 kernel, you have two options.
One is to switch to the HWE kernel, which is 4.15 for Ubuntu 16.04 - package `linux-image-generic-hwe-16.04` or similar.
Second, even better, upgrade to a newer release - 16.04 is EOL since last April and I'd be very surprised if you were trying to use `xow` on an operations-critical machine that cannot be upgraded ;)
